### PR TITLE
Feature/dynamic event positioning

### PR DESCRIPTION
**Pull request by vankeer**
Since @landru29 did not make a PRQ after issue #10, I made a fork myself to implement custom event element left/right positioning, using a new optional "side" attribute in the timeline-event directive.

### CODE REVIEW

**Comment by rpocklin** [comment]
Will get to this in the next week.

**Comment by armandchard** [comment]
I made the update to 1.6.0 but how to define if I want to align to left my timeline?

**Comment by vankeer** [comment]
@armandchard After the PRQ has been merged, or if you checkout my branch, you can set the alignment of the timeline events with the "side" attribute. 

From the example in https://github.com/vankeer/angular-timeline/blob/master/example/example.html :

```
<timeline-event ng-repeat="event in events" data-side="{{$index % 2 ? 'right' : 'left'}}">
```

**Comment by rpocklin** [comment]
It's coming in v1.6.1 hang in there :)

**Comment by armandchard** [comment]
Ok thanks both of you. 
I prefere to use a version packed with bower, it's easier to deploy my server. So I'm waiting v1.6.1

**Comment by rpocklin** [comment]
Landed in `v1.6.1`

@vankeer thanks for the PR, I didn't use your exact code so the PR doesn't appear merged.
There's also an example showing dynamic positioning using these attributes.

**Pull request closed without merging**
